######################################################################
##
## Filename: tb.udo
## Created on: Thu Oct 04 18:03:35 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
